---
title: "Main analysis"
author: "Jae Yeon Kim"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document:
    number_sections: yes
    fig_caption: yes
latex_engine: xelatex
link-citations: yes
linkcolor: blue
subparagraph: yes
citecolor: blue
urlcolor: blue
---

# Import pkgs and data 

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# install pkgs

if (!require(pacman)) install.packages("pacman")

pacman::p_load(
  tidyverse,
  glue,
  purrr,
  broom,
  patchwork,
  here,
  estimatr, 
  ggrepel,
  modelsummary, 
  marginaleffects,
  tidyhte, 
  fixest,
  glmnet
)

ggplot2::theme_set(theme_minimal())

if (!require(stdidx)) devtools::install_github("graemeblair/stdidx")
library(stdidx)

if (!require(tidyhte)) devtools::install_github("ddimmery/tidyhte")
library(tidyhte)

source(here("functions", "utils.R"))

df_string <- read_csv(here("raw_data", "HARV0049_OUTPUT_strings.csv"))
df_numeric <- read_csv(here("raw_data", "HARV0049_OUTPUT_numeric.csv"))
```

# Data summary 

## Categorical 

```{r}
datasummary_skim(df_string %>%
                   select(nat_origin, immigrant), 
                 type = "categorical",
                 output = here("outputs", "cat_data_summary.docx"))
```

## Numeric 

```{r}
df_num_sumamry <- create_dummies(df_numeric) %>%
  select(chinese_origin, immigrant, DEM, GOP, college, female, age)

df_num_sumamry$hate_crime_treatment <- df_string$hate_crime_treatment

datasummary(All(df_num_sumamry) ~ hate_crime_treatment * (Mean),
            data = df_num_sumamry, 
            output = here("outputs", "balance.docx"))
```

# ATE

```{r}
estimate_ate <- function(dv) {
  out <- lm_robust(eval(as.symbol(dv)) ~ factor(hate_crime_treatment), data = df_numeric) %>%
    tidy() %>%
    filter(!str_detect(term, "Int")) %>%
    mutate(outcome = dv)
  
  return(out)
}

ate_outs <- purrr::map_dfr(list("chinese_virus", "racial_linked_fate", "ethnic_linked_fate", "asian_racial_id", "asian_ethnic_id", "affirmative_action", "policy_crime"), estimate_ate) %>%
  mutate(term = case_when(
    str_detect(term, "4") ~ "Hate crime + political representation", 
    str_detect(term, "3") ~ "Hate crime + China threat", 
    str_detect(term, "2") ~ "Hate crime"
  )) 
```

## Linked fates 

```{r}
ate_outs %>% 
  filter(str_detect(outcome, "linked")) %>%
  mutate(outcome = case_when(
    str_detect(outcome, "racial") ~ "Racial linked fate", 
    str_detect(outcome, "ethnic") ~ "Ethnic linked fate"
  )) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low, col = outcome,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.4)) +
  coord_flip() +
  labs(
    title = "Linked fates",
    x = "", 
    y = "Estimated ATE",
    col = "Outcome") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.4)) 

ggsave(here("outputs", "lf_plots.png"), 
       height = 6, 
       width = 8)
```

```{r}
lf_mods <- list(
  "Ethnic linked fate" = feols(ethnic_linked_fate ~ factor(hate_crime_treatment), data = df_numeric, vcov = "hetero"),
  "Ethnic linked fate (weighted)" = feols(ethnic_linked_fate ~ factor(hate_crime_treatment), data = df_numeric, weights = ~weight, vcov = "hetero"),
  "Racial linked fate" = feols(racial_linked_fate ~ factor(hate_crime_treatment), data = df_numeric, vcov = "hetero"),
  "Racial linked fate (weighted)" = feols(racial_linked_fate ~ factor(hate_crime_treatment), data = df_numeric, weights = ~weight, vcov = "hetero")

)

mad_cm <- c(
  "factor(hate_crime_treatment)4" = "Hate crime + political representation", 
  "factor(hate_crime_treatment)3" = "Hate crime + China threat", 
  "factor(hate_crime_treatment)2" = "Hate crime"
)

modelsummary(lf_mods,
             estimate = c("{estimate}{stars} \n [{conf.low}, {conf.high}] \n p = {p.value}"),
             statistic = NULL,
             coef_map = mad_cm,
             coef_omit = "Intercept",
             output = here("outputs", "lf_mods.docx"))
```

## Identity importance 

```{r}
ate_outs %>% 
  filter(str_detect(outcome, "_id")) %>%
  mutate(outcome = case_when(
    str_detect(outcome, "racial") ~ "Racial ID importance", 
    str_detect(outcome, "ethnic") ~ "Ethnic ID importance"
  )) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low, col = outcome,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.4)) +
  coord_flip() +
  labs(
    title = "ID importance",
    x = "", 
    y = "Estimated ATE",
    col = "Outcome") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.4)) 

ggsave(here("outputs", "id_plots.png"), 
       height = 6, 
       width = 8)
```

## Chinese virus 

```{r}
ate_outs %>% 
  filter(str_detect(outcome, "_virus")) %>%
  mutate(outcome = case_when(
    str_detect(outcome, "chinese") ~ "Chinese virus"
  )) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.4)) +
  coord_flip() +
  labs(
    title = "Chinese virus",
    x = "", 
    y = "Estimated ATE") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.4)) 

ggsave(here("outputs", "cv_plot.png"), 
       height = 6, 
       width = 8)
```

## Policy outcomes

```{r}
ate_outs %>% 
  filter(str_detect(outcome, "action|crime")) %>%
  mutate(outcome = case_when(
    str_detect(outcome, "action") ~ "Affirmative action",
    str_detect(outcome, "crime") ~ "Police funding"
  )) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low, col = outcome,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.4)) +
  coord_flip() +
  labs(
    title = "Policy preferences",
    x = "", 
    y = "Estimated ATE",
    col = "Outcome") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.4)) 

ggsave(here("outputs", "policy_plots.png"), 
       height = 6, 
       width = 8)
```

# CATE

## Traditional approach

```{r}
# Chinese origin 
df_numeric$chinese_origin <- ifelse(df_numeric$nat_origin == 1, "Chinese", "Non-Chinese")

# Party ID
df_numeric$DEM <- ifelse(df_numeric$pid3 == 1 | df_numeric$pid7 %in% c(1, 3), "DEM", "Non-DEM")

df_numeric$GOP <- ifelse(df_numeric$pid3 == 3 | df_numeric$pid7 %in% c(7, 5), "GOP", "Non-GOP")

# Immigrant
df_numeric$immigrant <- ifelse(df_numeric$immigrant %in% c(1, 2), "Immigrant", "Non-immigrant")

# College
df_numeric$college <- ifelse(df_numeric$educ %in% c(3:6), "College", "Non-college")

# Male
df_numeric$female <- ifelse(df_numeric$gender4 == 2, "Female", "Else")
```

```{r}
# China threat index 
df_numeric$china_threat_index <- idx_mean(df_numeric$china_threat_1_rule, df_numeric$china_threat_2_rule, df_numeric$china_threat_3_rule)

df_numeric$china_threatend_high <- ifelse(df_numeric$china_threat_index > median(df_numeric$china_threat_index), "High", "Median and Low")

# Democracy conception
df_numeric$democracy_sub <- idx_mean(df_numeric$democracy_meaning_1 + df_numeric$democracy_meaning_2 + df_numeric$democracy_meaning_3)

df_numeric$democracy_cat <- ifelse(df_numeric$democracy_sub > median(df_numeric$democracy_sub), "High", "Median and Low")
```

```{r}
ols <- function(df, dv) { 
  
  lm_robust(eval(as.symbol(dv)) ~ factor(hate_crime_treatment), data = df) %>%
    tidy() %>%
    filter(!str_detect(term, "Int")) %>%
    mutate(outcome = dv)
  
}

nest_ols <- function(df, dv) {
  
  df %>%
    nest() %>%
    mutate(ols = map(data, ~ols(., dv))) %>%
    unnest(ols) %>% 
    mutate(term = case_when(
      str_detect(term, "4") ~ "Hate crime + political representation", 
      str_detect(term, "3") ~ "Hate crime + China threat", 
      str_detect(term, "2") ~ "Hate crime"
    )) %>%
    mutate(outcome = case_when(
      str_detect(outcome, "racial") ~ "Racial linked fate", 
      str_detect(outcome, "ethnic") ~ "Ethnic linked fate"
    ))  
}
```

```{r}
chinese_cate_plot <- bind_rows(
  df_numeric %>%
    group_by(chinese_origin) %>%
    nest_ols("racial_linked_fate"),
  df_numeric %>%
    group_by(chinese_origin) %>%
    nest_ols("ethnic_linked_fate")
  ) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low, col = chinese_origin,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  coord_flip() +
  labs(
    title = "Chinese v Non-Chinese",
    x = "", 
    y = "Estimated ATE",
    col = "Subgroup") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  theme(legend.position = "right") +
  facet_wrap(~outcome)

china_threat_perc_plot <- bind_rows(
  df_numeric %>%
    group_by(china_threatend_high) %>%
    nest_ols("racial_linked_fate"),
  df_numeric %>%
    group_by(china_threatend_high) %>%
    nest_ols("ethnic_linked_fate")
  ) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low, col = china_threatend_high,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  coord_flip() +
  labs(
    title = "Perceived China threat",
    x = "", 
    y = "Estimated ATE",
    col = "Subgroup") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  theme(legend.position = "right") +
  facet_wrap(~outcome)

dem_perc_plot <- bind_rows(
  df_numeric %>%
    group_by(democracy_cat) %>%
    nest_ols("racial_linked_fate"),
  df_numeric %>%
    group_by(democracy_cat) %>%
    nest_ols("ethnic_linked_fate")
  ) %>%
  ggplot(aes(x = term, y = estimate, ymax = conf.high, ymin = conf.low, col = democracy_cat,
             label = round(estimate, 2))) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  coord_flip() +
  labs(
    title = "Democracy perception",
    x = "", 
    y = "Estimated ATE",
    col = "Subgroup") +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed")  +
  scale_color_grey(start = 0.3, end = 0.7) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  theme(legend.position = "right") +
  facet_wrap(~outcome)

cate_rl_plots <- chinese_cate_plot / china_threat_perc_plot / dem_perc_plot + plot_annotation(tag_levels = "a")

cate_rl_plots

ggsave(plot = cate_rl_plots, 
       filename = here("outputs", "cate_rl_plots.png"), 
       height = 12, 
       width = 10)
```

## Double roubst learner

```{r}
# racial linked fate
t2_rl_results <- get_db_rl_estimates(2)
t3_rl_results <- get_db_rl_estimates(3)
t4_rl_results <- get_db_rl_estimates(4)

# ethnic linked fate
t2_el_results <- get_db_el_estimates(2)
t3_el_results <- get_db_el_estimates(3)
t4_el_results <- get_db_el_estimates(4)
```

```{r}
rl_results <- reduce(list(
  t2_rl_results %>%
    mutate(treatment = "Hate crime"), 
  t3_rl_results %>%
    mutate(treatment = "Hate crime + China threat"), 
  t4_rl_results %>%
    mutate(treatment = "Hate crime + political representation")), bind_rows) %>%
  mutate(outcome = "Racial linked fate")
```

```{r}
el_results <- reduce(list(
  t2_el_results %>%
    mutate(treatment = "Hate crime"), 
  t3_el_results %>%
    mutate(treatment = "Hate crime + China threat"), 
  t4_el_results %>%
    mutate(treatment = "Hate crime + political representation")), bind_rows) %>%
  mutate(outcome = "Ethnic linked fate")

results <- bind_rows(rl_results, el_results)
```

## Load 

```{r}
write_csv(results, here("processed_data", "cate_results.csv"))

results <- read_csv(here("processed_data", "cate_results.csv"))
```

## Pre-registered

```{r}
#chinese_origin, democracy_cat, china_threatend_high, DEM, GOP

cn_origin_plot <- results %>%
  filter(estimand == "MCATE") %>%
  filter(term == "chinese_origin") %>%
  ggplot(aes(x = treatment, 
             y = estimate, 
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             col = level,
             label = round(estimate, 2))) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  facet_wrap(~outcome) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  scale_x_discrete("Covariate level") +
  scale_y_continuous("Estimated CATE") +
  labs(col = "Subgroup",
       title = "Marginal effects across Chinese dummy") +
  coord_flip() +
  scale_color_grey(start = 0.3, end = 0.7)

dem_pec_plot <- results %>%
  filter(estimand == "MCATE") %>%
  filter(term == "democracy_cat") %>%
  ggplot(aes(x = treatment, 
             y = estimate, 
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             col = level,
             label = round(estimate, 2))) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  facet_wrap(~outcome) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  scale_x_discrete("Covariate level") +
  scale_y_continuous("Estimated CATE") +
  labs(col = "Subgroup",
       title = "Marginal effects across substantive democracy perception") +
  coord_flip() +
  scale_color_grey(start = 0.3, end = 0.7)

cn_threat_plot <- results %>%
  filter(estimand == "MCATE") %>%
  filter(term == "china_threatend_high") %>%
   ggplot(aes(x = treatment, 
             y = estimate, 
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             col = level,
             label = round(estimate, 2))) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  facet_wrap(~outcome) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  scale_x_discrete("Covariate level") +
  scale_y_continuous("Estimated CATE") +
  labs(col = "Subgroup",
       title = "Marginal effects across perceived China threat") +
  coord_flip() +
  scale_color_grey(start = 0.3, end = 0.7)
```

## Non-registered

```{r}
pid_plot <- results %>%
  filter(estimand == "MCATE") %>%
  filter(term %in% c("DEM", "GOP")) %>%
  filter(!str_detect(level, "Non")) %>%
  ggplot(aes(x = treatment, 
             y = estimate, 
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             col = level,
             label = round(estimate, 2))) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  facet_wrap(~outcome) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  scale_x_discrete("Covariate level") +
  scale_y_continuous("Estimated CATE") +
  scale_color_manual(values = c("blue", "red")) +
  labs(col = "Subgroup",
       title = "Marginal effects across party ID") +
  coord_flip() +
  theme(legend.position = "bottom")
```

```{r}
immigrant_plot <- results %>%
  filter(estimand == "MCATE") %>%
  filter(term == "immigrant") %>%
  ggplot(aes(x = treatment, 
             y = estimate, 
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             col = level,
             label = round(estimate, 2))) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  facet_wrap(~outcome) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  scale_x_discrete("Covariate level") +
  scale_y_continuous("Estimated CATE") +
  labs(col = "Subgroup",
       title = "Marginal effects across immigrant status") +
  scale_color_grey(start = 0.3, end = 0.7) +
  coord_flip() +
  theme(legend.position = "bottom")

college_plot <- results %>%
  filter(estimand == "MCATE") %>%
  filter(term == "college") %>%
  ggplot(aes(x = treatment, 
             y = estimate, 
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             col = level,
             label = round(estimate, 2))) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  facet_wrap(~outcome) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  scale_x_discrete("Covariate level") +
  scale_y_continuous("Estimated CATE") +
  labs(col = "Subgroup",
       title = "Marginal effects across college education status") +
  scale_color_grey(start = 0.3, end = 0.7) +
  coord_flip() +
  theme(legend.position = "bottom")
```

## Pooled 

```{r}
results_pooled <- results %>%
  filter(estimand == "MCATE")

results_pooled$level[results_pooled$term == "democracy_cat"] <- rep(c("Median and low democracy perception", "High democracy perception"), 6)

results_pooled$level[results_pooled$term == "china_threatend_high"] <- rep(c("Median and low China threat perception", "High China threat perception"), 6)
```

```{r}
pooled_cate_plot <- results_pooled %>%
  filter(!str_detect(level, "Non-G|Non-D")) %>%
  mutate(significant = ifelse(estimate - 1.96 * std_error > 0, "Significant", "Non-significant")) %>%
  ggplot(aes(x = fct_reorder(level, estimate), 
             y = estimate,
             ymin = estimate - 1.96 * std_error,
             ymax = estimate + 1.96 * std_error,
             label = round(estimate, 2), 
             col = significant)) +
  geom_pointrange(position = position_dodge(width = 0.2)) +
  geom_text_repel(position = position_dodge(width = 0.2)) +
  coord_flip() +
  facet_grid(outcome~treatment) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  labs(x = "",
       y = "Estimated CATE",
       col = "Statistical significance") +
  theme(legend.position = "bottom") +
  scale_color_grey(start = 0.7, end = 0.3) 

pooled_cate_plot
```

## Save

```{r}
hte_plots <- cn_origin_plot / cn_threat_plot / dem_pec_plot + plot_annotation(tag_levels = "a")

png(filename = here("outputs", "hte_plots.png"), 
    height = 12, 
    width = 10, 
    unit = "in", 
    res = 1200)

hte_plots 

dev.off()
```

```{r}
png(filename = here("outputs", "hte_plots_pid.png"), 
    height = 6, 
    width = 6, 
    unit = "in", 
    res = 1200)

pid_plot 

dev.off()
```

```{r}
hte_plots_others <- immigrant_plot / college_plot + plot_annotation(tag_levels = "a")

png(filename = here("outputs", "hte_plots_others.png"), 
    height = 12, 
    width = 10, 
    unit = "in", 
    res = 1200)

hte_plots_others

dev.off()
```

```{r}
png(filename = here("outputs", "pooled_cate_plot.png"), 
    height = 12, 
    width = 10, 
    unit = "in", 
    res = 1200)

pooled_cate_plot

dev.off()
```

# Open-ended texts

```{r}
df_string$
```